FROM ghcr.io/cirruslabs/flutter:3.35.4 AS build

WORKDIR /app
COPY pubspec.yaml pubspec.lock ./
RUN flutter pub get

COPY . .
RUN flutter pub get \
    && flutter build web --release --base-href /

FROM nginx:alpine
COPY --from=build /app/build/web /usr/share/nginx/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/web/download/bazarek.apk /usr/share/nginx/html/download/bazarek.apk
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
