import 'dart:convert';
import 'dart:typed_data';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'api_service.dart';

void main() => runApp(const BazarekApp());

class BazarekApp extends StatelessWidget {
  const BazarekApp({super.key});
  @override
  Widget build(BuildContext context) => MaterialApp(
    title: 'بازارک', debugShowCheckedModeBanner: false, locale: const Locale('fa'),
    theme: ThemeData(useMaterial3: true, colorSchemeSeed: Colors.teal, fontFamily: 'Roboto'),
    home: const StartupScreen(),
  );
}

class StartupScreen extends StatefulWidget { const StartupScreen({super.key}); @override State<StartupScreen> createState()=>_StartupScreenState(); }
class _StartupScreenState extends State<StartupScreen> {
  @override void initState(){super.initState();_start();}
  Future<void> _start() async { final p=await SharedPreferences.getInstance(); final t=p.getString('bazarek_token'); if(t!=null&&t.isNotEmpty){ApiService.setToken(t);try{await ApiService.getProfile();if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const HomeScreen()));return;}catch(_){await p.remove('bazarek_token');ApiService.setToken(null);}}if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>const HomeScreen())); }
  @override Widget build(BuildContext context)=>const Scaffold(body:Center(child:CircularProgressIndicator()));
}

class HomeScreen extends StatefulWidget { const HomeScreen({super.key}); @override State<HomeScreen> createState()=>_HomeScreenState(); }
class _HomeScreenState extends State<HomeScreen>{
  final search=TextEditingController(); List<Map<String,dynamic>> listings=[]; bool loading=true; String category='';
  final cats=['همه','موبایل','موتر','املاک','لوازم برقی','خانه','لباس','خدمات','کار','حیوانات'];
  @override void initState(){super.initState();_load();}
  Future<void> _load()async{if(mounted)setState(()=>loading=true);try{final x=await ApiService.getListings(q:search.text,category:category=='همه'?'':category);if(mounted)setState(()=>listings=x);}catch(e){if(mounted)_msg(e);}finally{if(mounted)setState(()=>loading=false);}}
  void _msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));
  Future<void> _openLogin()async{await Navigator.push(context,MaterialPageRoute(builder:(_)=>const LoginScreen()));if(mounted)_load();}
  Future<void> _openAccount()async{final p=await SharedPreferences.getInstance();if(p.getString('bazarek_token')==null){await _openLogin();return;}if(!mounted)return;Navigator.push(context,MaterialPageRoute(builder:(_)=>const DashboardScreen()));}
  Future<void> _post()async{final p=await SharedPreferences.getInstance();if(p.getString('bazarek_token')==null){await _openLogin();return;}if(!mounted)return;Navigator.push(context,MaterialPageRoute(builder:(_)=>const DashboardScreen()));}
  @override Widget build(BuildContext context)=>Scaffold(
    appBar:AppBar(title:const Text('بازارک',style:TextStyle(fontWeight:FontWeight.bold)),actions:[IconButton(onPressed:_openAccount,tooltip:'حساب من',icon:const Icon(Icons.person_outline))]),
    floatingActionButton:FloatingActionButton.extended(onPressed:_post,icon:const Icon(Icons.add),label:const Text('ثبت آگهی')),
    body:RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.fromLTRB(16,8,16,100),children:[
      Text('بازار افغانستان، ساده و حرفه‌ای',style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.bold)),
      const SizedBox(height:12),TextField(controller:search,onSubmitted:(_)=>_load(),textInputAction:TextInputAction.search,decoration:InputDecoration(hintText:'چه چیزی می‌خواهید پیدا کنید؟',prefixIcon:const Icon(Icons.search),suffixIcon:IconButton(onPressed:_load,icon:const Icon(Icons.tune)),border:OutlineInputBorder(borderRadius:BorderRadius.circular(18)))),
      const SizedBox(height:12),SizedBox(height:44,child:ListView.separated(scrollDirection:Axis.horizontal,itemCount:cats.length,itemBuilder:(_,i)=>ChoiceChip(label:Text(cats[i]),selected:(category.isEmpty&&i==0)||category==cats[i],onSelected:(_){setState(()=>category=cats[i]);_load();}),separatorBuilder:(_,__)=>const SizedBox(width:8))),
      const SizedBox(height:18),if(loading)const Center(child:Padding(padding:EdgeInsets.all(30),child:CircularProgressIndicator())) else if(listings.isEmpty)const Card(child:Padding(padding:EdgeInsets.all(28),child:Column(children:[Icon(Icons.search_off,size:46),SizedBox(height:8),Text('آگهی‌ای پیدا نشد.'),Text('جستجو یا دسته‌بندی را تغییر دهید.')]))) else ...listings.map((p)=>ListingCard(product:p,onTap:()=>_details(p)))
    ])));
  void _details(Map<String,dynamic> p)=>showModalBottomSheet(context:context,isScrollControlled:true,builder:(_)=>Directionality(textDirection:TextDirection.rtl,child:SingleChildScrollView(padding:const EdgeInsets.fromLTRB(20,20,20,32),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
    ImageGallery(images:_imageUrls(p['image_url']),height:230),const SizedBox(height:14),Text(p['title']??'',style:const TextStyle(fontSize:24,fontWeight:FontWeight.bold)),const SizedBox(height:12),
    Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Theme.of(context).colorScheme.surfaceContainerHighest,borderRadius:BorderRadius.circular(14)),child:Row(mainAxisAlignment:MainAxisAlignment.spaceBetween,children:[const Text('قیمت',style:TextStyle(fontSize:16)),Text(_money(p['price']),style:const TextStyle(fontSize:21,fontWeight:FontWeight.bold))])),
    if((p['category']??'').toString().isNotEmpty)Padding(padding:const EdgeInsets.only(top:12),child:Text('دسته‌بندی: ${p['category']}')),const SizedBox(height:12),const Text('توضیحات',style:TextStyle(fontSize:17,fontWeight:FontWeight.bold)),const SizedBox(height:6),Text((p['description']??'توضیحی ثبت نشده است.').toString(),style:const TextStyle(height:1.6)),
    const SizedBox(height:18),SizedBox(width:double.infinity,child:FilledButton.icon(onPressed:()=>_msg(Exception('برای تماس و چت، وارد حساب شوید.')),icon:const Icon(Icons.chat_bubble_outline),label:const Text('چت با فروشنده')))
  ]))));
}

List<String> _imageUrls(dynamic raw){
  final s=(raw??'').toString().trim(); if(s.isEmpty)return [];
  try{final d=jsonDecode(s);if(d is List)return d.map((e)=>e.toString()).where((e)=>e.isNotEmpty).toList();}catch(_){ }
  return [s];
}
String _money(dynamic value){final n=(value is num)?value:double.tryParse('$value')??0;return '${n.toStringAsFixed(n%1==0?0:2)} افغانی';}

class ImageGallery extends StatelessWidget{final List<String> images;final double height;const ImageGallery({super.key,required this.images,this.height=180});@override Widget build(BuildContext context){if(images.isEmpty)return Container(height:height,decoration:BoxDecoration(color:Theme.of(context).colorScheme.surfaceContainerHighest,borderRadius:BorderRadius.circular(16)),child:const Icon(Icons.image_outlined,size:48));return SizedBox(height:height,child:PageView.builder(itemCount:images.length,itemBuilder:(_,i)=>Padding(padding:const EdgeInsets.symmetric(horizontal:2),child:ClipRRect(borderRadius:BorderRadius.circular(16),child:Image.network(images[i],fit:BoxFit.cover,errorBuilder:(_,__,___)=>const Center(child:Icon(Icons.broken_image,size:42))))));}}
class ListingCard extends StatelessWidget{final Map<String,dynamic> product;final VoidCallback onTap;const ListingCard({super.key,required this.product,required this.onTap});@override Widget build(BuildContext context){final images=_imageUrls(product['image_url']);return Card(clipBehavior:Clip.antiAlias,margin:const EdgeInsets.only(bottom:10),child:InkWell(onTap:onTap,child:Padding(padding:const EdgeInsets.all(10),child:Row(crossAxisAlignment:CrossAxisAlignment.start,children:[ClipRRect(borderRadius:BorderRadius.circular(12),child:images.isNotEmpty?Image.network(images.first,width:86,height:86,fit:BoxFit.cover,errorBuilder:(_,__,___)=>_placeholder(context)):_placeholder(context)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[if(product['is_pinned']==true)const Icon(Icons.push_pin,size:17),if(product['is_featured']==true)const Icon(Icons.star,size:17),const SizedBox(width:3),Expanded(child:Text((product['title']??'').toString(),maxLines:2,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:16,fontWeight:FontWeight.w700)))]),const SizedBox(height:8),Text((product['category']??'عمومی').toString()),const SizedBox(height:8),Text(_money(product['price']),style:TextStyle(fontSize:17,fontWeight:FontWeight.bold,color:Theme.of(context).colorScheme.primary))])),const Icon(Icons.chevron_left)]))));}Widget _placeholder(BuildContext context)=>Container(width:86,height:86,decoration:BoxDecoration(color:Theme.of(context).colorScheme.surfaceContainerHighest,borderRadius:BorderRadius.circular(12)),child:const Icon(Icons.image_outlined,size:34));}

class LoginScreen extends StatefulWidget { const LoginScreen({super.key}); @override State<LoginScreen> createState()=>_LoginScreenState(); }
class _LoginScreenState extends State<LoginScreen>{final email=TextEditingController(),password=TextEditingController();bool loading=false;Future<void> _login()async{setState(()=>loading=true);try{final t=await ApiService.login(email.text.trim(),password.text);final p=await SharedPreferences.getInstance();await p.setString('bazarek_token',t);if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const HomeScreen()),(_)=>false);}catch(e){_msg(e);}finally{if(mounted)setState(()=>loading=false);}}void _msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));@override Widget build(BuildContext context)=>AuthScaffold(title:'ورود به بازارک',children:[TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'ایمیل',prefixIcon:Icon(Icons.email_outlined),border:OutlineInputBorder())),const SizedBox(height:14),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'رمز عبور',prefixIcon:Icon(Icons.lock_outline),border:OutlineInputBorder())),const SizedBox(height:20),SizedBox(width:double.infinity,height:52,child:FilledButton(onPressed:loading?null:_login,child:loading?const CircularProgressIndicator():const Text('ورود'))),TextButton(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const RegisterScreen())),child:const Text('حساب ندارید؟ ثبت‌نام کنید')),const Divider(height:28),TextButton.icon(onPressed:()=>Navigator.push(context,MaterialPageRoute(builder:(_)=>const AdminLoginScreen())),icon:const Icon(Icons.admin_panel_settings_outlined),label:const Text('ورود مدیریت'))]);}

class AdminLoginScreen extends StatefulWidget{const AdminLoginScreen({super.key});@override State<AdminLoginScreen> createState()=>_AdminLoginScreenState();}
class _AdminLoginScreenState extends State<AdminLoginScreen>{final email=TextEditingController(),password=TextEditingController();bool loading=false;Future<void> _login()async{setState(()=>loading=true);try{final t=await ApiService.adminLogin(email.text.trim(),password.text);final p=await SharedPreferences.getInstance();await p.setString('bazarek_admin_token',t);if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>AdminDashboardScreen(token:t)));}catch(e){ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext context)=>AuthScaffold(title:'پنل مدیریت بازارک',children:[const Text('این بخش فقط برای مدیر سیستم است.',textAlign:TextAlign.center),const SizedBox(height:20),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'ایمیل مدیر',border:OutlineInputBorder())),const SizedBox(height:12),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'رمز عبور مدیر',border:OutlineInputBorder())),const SizedBox(height:18),SizedBox(height:52,child:FilledButton(onPressed:loading?null:_login,child:loading?const CircularProgressIndicator():const Text('ورود امن به مدیریت')))]);}

class AdminDashboardScreen extends StatefulWidget{final String token;const AdminDashboardScreen({super.key,required this.token});@override State<AdminDashboardScreen> createState()=>_AdminDashboardScreenState();}
class _AdminDashboardScreenState extends State<AdminDashboardScreen>{Map<String,dynamic> stats={};List<Map<String,dynamic>> products=[];List<Map<String,dynamic>> users=[];bool loading=true;int tab=0;
 Future<void> _load()async{setState(()=>loading=true);try{final r=await Future.wait([ApiService.adminStats(widget.token),ApiService.adminProducts(widget.token),ApiService.adminUsers(widget.token)]);if(mounted)setState((){stats=r[0] as Map<String,dynamic>;products=r[1] as List<Map<String,dynamic>>;users=r[2] as List<Map<String,dynamic>>;});}catch(e){_err(e);}finally{if(mounted)setState(()=>loading=false);}}
 Future<void> _status(Map<String,dynamic> p,bool active)async{try{await ApiService.adminSetProductStatus(widget.token,p['id'].toString(),active);await _load();}catch(e){_err(e);}}
 Future<void> _delete(String id)async{try{await ApiService.adminDeleteProduct(widget.token,id);await _load();}catch(e){_err(e);}}
 Future<void> _promote(Map<String,dynamic> p)async{final choice=await showDialog<String>(context:context,builder:(_)=>SimpleDialog(title:const Text('ارتقای آگهی'),children:[SimpleDialogOption(onPressed:()=>Navigator.pop(context,'featured7'),child:const Text('⭐ ویژه ۷ روزه')),SimpleDialogOption(onPressed:()=>Navigator.pop(context,'featured30'),child:const Text('⭐ ویژه ۳۰ روزه')),SimpleDialogOption(onPressed:()=>Navigator.pop(context,'pin7'),child:const Text('📌 پین ۷ روزه')),SimpleDialogOption(onPressed:()=>Navigator.pop(context,'pin30'),child:const Text('📌 پین ۳۰ روزه')),SimpleDialogOption(onPressed:()=>Navigator.pop(context,'both7'),child:const Text('⭐📌 ویژه + پین ۷ روزه')),SimpleDialogOption(onPressed:()=>Navigator.pop(context,'clear'),child:const Text('حذف ارتقا'))]));if(choice==null)return;int f=0,pi=0;if(choice=='featured7')f=7;if(choice=='featured30')f=30;if(choice=='pin7')pi=7;if(choice=='pin30')pi=30;if(choice=='both7'){f=7;pi=7;}try{await ApiService.adminPromoteProduct(widget.token,p['id'].toString(),featureDays:f,pinDays:pi);await _load();}catch(e){_err(e);}}
 Future<void> _block(Map<String,dynamic> u)async{final blocked=u['is_blocked']==true;if(blocked){try{await ApiService.adminBlockUser(widget.token,u['id'].toString(),blocked:false);await _load();}catch(e){_err(e);}return;}final days=await showDialog<int>(context:context,builder:(_)=>SimpleDialog(title:const Text('مسدود کردن کاربر'),children:[SimpleDialogOption(onPressed:()=>Navigator.pop(context,1),child:const Text('۱ روز')),SimpleDialogOption(onPressed:()=>Navigator.pop(context,7),child:const Text('۷ روز')),SimpleDialogOption(onPressed:()=>Navigator.pop(context,30),child:const Text('۳۰ روز')),SimpleDialogOption(onPressed:()=>Navigator.pop(context,0),child:const Text('دائمی'))]));if(days==null)return;final reason=await _reasonDialog();try{await ApiService.adminBlockUser(widget.token,u['id'].toString(),blocked:true,durationDays:days,reason:reason);await _load();}catch(e){_err(e);}}
 Future<String> _reasonDialog()async{final c=TextEditingController();final r=await showDialog<String>(context:context,builder:(_)=>AlertDialog(title:const Text('دلیل مسدودی'),content:TextField(controller:c,maxLines:3,decoration:const InputDecoration(hintText:'مثلاً توهین، کلاهبرداری یا محتوای خلاف قوانین')),actions:[TextButton(onPressed:()=>Navigator.pop(context,''),child:const Text('بدون دلیل')),FilledButton(onPressed:()=>Navigator.pop(context,c.text.trim()),child:const Text('ثبت'))]));return r??'';}
 void _err(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));
 Future<void> _logout()async{final p=await SharedPreferences.getInstance();await p.remove('bazarek_admin_token');if(mounted)Navigator.pop(context);}
 @override void initState(){super.initState();_load();}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('مدیریت بازارک'),actions:[IconButton(onPressed:_load,icon:const Icon(Icons.refresh)),IconButton(onPressed:_logout,icon:const Icon(Icons.logout))]),body:RefreshIndicator(onRefresh:_load,child:ListView(padding:const EdgeInsets.all(16),children:[if(loading)const LinearProgressIndicator(),const SizedBox(height:8),GridView.count(shrinkWrap:true,physics:const NeverScrollableScrollPhysics(),crossAxisCount:2,childAspectRatio:1.7,children:[_stat('کاربران',stats['users']??0,Icons.people_outline),_stat('آگهی‌ها',stats['products']??0,Icons.campaign_outlined)]),const SizedBox(height:14),SegmentedButton<int>(segments:const[ButtonSegment(value:0,label:Text('آگهی‌ها'),icon:Icon(Icons.campaign_outlined)),ButtonSegment(value:1,label:Text('کاربران'),icon:Icon(Icons.people_outline))],selected:{tab},onSelectionChanged:(v)=>setState(()=>tab=v.first)),const SizedBox(height:16),if(tab==0)...products.map((p)=>Card(child:ListTile(leading:Icon(p['is_pinned']==true?Icons.push_pin:p['is_featured']==true?Icons.star:p['is_active']==true?Icons.visibility:Icons.visibility_off),title:Text(p['title']??''),subtitle:Text('${_money(p['price'])} • ${p['category']??'بدون دسته'}'),trailing:PopupMenuButton<String>(onSelected:(v){if(v=='active')_status(p,true);if(v=='off')_status(p,false);if(v=='promote')_promote(p);if(v=='delete')_delete(p['id'].toString());},itemBuilder:(_)=>const[PopupMenuItem(value:'active',child:Text('فعال کردن')),PopupMenuItem(value:'off',child:Text('غیرفعال کردن')),PopupMenuItem(value:'promote',child:Text('⭐ ویژه / 📌 پین')),PopupMenuItem(value:'delete',child:Text('حذف آگهی'))])))) else ...users.map((u)=>Card(child:ListTile(leading:Icon(u['is_blocked']==true?Icons.block:Icons.person_outline),title:Text((u['shop_name']??u['full_name']??'کاربر بدون نام').toString()),subtitle:Text('${u['phone']??''}${u['block_reason']!=null?' • ${u['block_reason']}':''}'),trailing:FilledButton.tonal(onPressed:()=>_block(u),child:Text(u['is_blocked']==true?'رفع مسدودی':'مسدود کردن')))))])));
 Widget _stat(String t,dynamic v,IconData i)=>Card(child:Padding(padding:const EdgeInsets.all(14),child:Row(children:[Icon(i),const SizedBox(width:8),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t),Text('$v',style:const TextStyle(fontSize:21,fontWeight:FontWeight.bold))])])));
}

class RegisterScreen extends StatefulWidget { const RegisterScreen({super.key}); @override State<RegisterScreen> createState()=>_RegisterScreenState(); }
class _RegisterScreenState extends State<RegisterScreen>{final name=TextEditingController(),shop=TextEditingController(),phone=TextEditingController(),email=TextEditingController(),password=TextEditingController();bool loading=false;Future<void> _register()async{if(password.text.length<8){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('رمز عبور باید حداقل ۸ کاراکتر باشد.')));return;}setState(()=>loading=true);try{final d=await ApiService.register(email:email.text.trim(),password:password.text,fullName:name.text,shopName:shop.text,phone:phone.text);final token=d['token'];if(token!=null){final p=await SharedPreferences.getInstance();await p.setString('bazarek_token',token.toString());if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const HomeScreen()),(_)=>false);}else{throw Exception('حساب ساخته نشد. لطفاً دوباره تلاش کنید.');}}catch(e){if(mounted)ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));}finally{if(mounted)setState(()=>loading=false);}}@override Widget build(BuildContext context)=>AuthScaffold(title:'ساخت حساب',children:[TextField(controller:name,decoration:const InputDecoration(labelText:'نام شما',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:shop,decoration:const InputDecoration(labelText:'نام دکان / کسب‌وکار',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'شماره تماس',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:email,keyboardType:TextInputType.emailAddress,decoration:const InputDecoration(labelText:'ایمیل',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'رمز عبور (حداقل ۸ کاراکتر)',border:OutlineInputBorder())),const SizedBox(height:18),SizedBox(height:52,child:FilledButton(onPressed:loading?null:_register,child:loading?const CircularProgressIndicator():const Text('ساخت حساب و ورود')))]);}

class DashboardScreen extends StatefulWidget { const DashboardScreen({super.key}); @override State<DashboardScreen> createState()=>_DashboardScreenState(); }
class _DashboardScreenState extends State<DashboardScreen>{List<Map<String,dynamic>> products=[];Map<String,dynamic>? profile;bool loading=true;@override void initState(){super.initState();_load();}Future<void> _load()async{try{final r=await Future.wait([ApiService.getProducts(),ApiService.getProfile()]);if(mounted)setState((){products=r[0] as List<Map<String,dynamic>>;profile=r[1] as Map<String,dynamic>;loading=false;});}catch(e){if(mounted){setState(()=>loading=false);_msg(e);}}}void _msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));Future<void> _add()async{final result=await showModalBottomSheet<Map<String,dynamic>>(context:context,isScrollControlled:true,builder:(_)=>const AddProductSheet());if(result==null)return;try{await ApiService.addProduct(result);await _load();}catch(e){_msg(e);}}Future<void> _delete(String id)async{try{await ApiService.deleteProduct(id);await _load();}catch(e){_msg(e);}}Future<void> _logout()async{final p=await SharedPreferences.getInstance();await p.remove('bazarek_token');ApiService.setToken(null);if(mounted)Navigator.pushAndRemoveUntil(context,MaterialPageRoute(builder:(_)=>const HomeScreen()),(_)=>false);}@override Widget build(BuildContext context){final shop=(profile?['shop_name']??'').toString();return Scaffold(appBar:AppBar(title:Text(shop.isEmpty?'حساب من':shop),actions:[IconButton(onPressed:_logout,icon:const Icon(Icons.logout))]),floatingActionButton:FloatingActionButton.extended(onPressed:_add,icon:const Icon(Icons.add),label:const Text('ثبت آگهی')),body:RefreshIndicator(onRefresh:_load,child:loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(16),children:[Text('سلام ${profile?['full_name']??''} 👋',style:const TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:16),Row(children:[_stat('آگهی‌های من',products.length.toString(),Icons.campaign_outlined),const SizedBox(width:10),_stat('موجودی',products.fold<int>(0,(s,p)=>s+((p['stock'] as num?)??0).toInt()).toString(),Icons.inventory_2_outlined)]),const SizedBox(height:20),...products.map((p)=>Card(child:ListTile(leading:ImageGallery(images:_imageUrls(p['image_url']),height:55),title:Text(p['title']??''),subtitle:Text(_money(p['price'])),trailing:IconButton(onPressed:()=>_delete(p['id'].toString()),icon:const Icon(Icons.delete_outline)))))]));}Widget _stat(String t,String v,IconData i)=>Expanded(child:Card(child:Padding(padding:const EdgeInsets.all(14),child:Row(children:[Icon(i),const SizedBox(width:8),Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t),Text(v,style:const TextStyle(fontSize:21,fontWeight:FontWeight.bold))])]))));}

class AddProductSheet extends StatefulWidget{const AddProductSheet({super.key});@override State<AddProductSheet> createState()=>_AddProductSheetState();}
class _AddProductSheetState extends State<AddProductSheet>{final title=TextEditingController(),price=TextEditingController(),stock=TextEditingController(text:'1'),desc=TextEditingController();String category='';List<Uint8List> imageBytes=[];List<String> imageNames=[];List<String> imageUrls=[];bool uploading=false;final picker=ImagePicker();final cats=['موبایل','موتر','املاک','لوازم برقی','خانه','لباس','خدمات','کار','حیوانات','سایر'];
 Future<void> _pickImages()async{try{final xs=await picker.pickMultiImage(imageQuality:80,maxWidth:1600);if(xs.isEmpty)return;final selected=xs.take(6).toList();final bytes=<Uint8List>[];final names=<String>[];for(final x in selected){bytes.add(await x.readAsBytes());names.add(x.name);}setState((){imageBytes=bytes;imageNames=names;imageUrls=[];});}catch(e){_msg(e);}}
 Future<void> _uploadImages()async{if(imageBytes.isEmpty)return;setState(()=>uploading=true);try{imageUrls=await ApiService.uploadImages(imageBytes,imageNames);if(mounted)setState((){});}catch(e){_msg(e);}finally{if(mounted)setState(()=>uploading=false);}}
 void _msg(Object e)=>ScaffoldMessenger.of(context).showSnackBar(SnackBar(content:Text(e.toString().replaceFirst('Exception: ',''))));
 @override Widget build(BuildContext context)=>Padding(padding:EdgeInsets.only(left:20,right:20,top:20,bottom:MediaQuery.of(context).viewInsets.bottom+20),child:SingleChildScrollView(child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[
   const Text('ثبت آگهی',style:TextStyle(fontSize:22,fontWeight:FontWeight.bold)),const SizedBox(height:8),const Text('حداکثر ۶ عکس می‌توانید برای هر آگهی اضافه کنید.'),const SizedBox(height:14),
   InkWell(onTap:_pickImages,child:Container(height:170,decoration:BoxDecoration(color:Theme.of(context).colorScheme.surfaceContainerHighest,borderRadius:BorderRadius.circular(16)),child:imageBytes.isEmpty?const Column(mainAxisAlignment:MainAxisAlignment.center,children:[Icon(Icons.add_photo_alternate_outlined,size:48),SizedBox(height:8),Text('انتخاب عکس‌ها'),Text('حداکثر ۶ عکس')]):GridView.builder(padding:const EdgeInsets.all(8),itemCount:imageBytes.length,gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3,crossAxisSpacing:8,mainAxisSpacing:8),itemBuilder:(_,i)=>ClipRRect(borderRadius:BorderRadius.circular(10),child:Image.memory(imageBytes[i],fit:BoxFit.cover)))),
   if(imageBytes.isNotEmpty)Padding(padding:const EdgeInsets.only(top:10),child:OutlinedButton.icon(onPressed:uploading?null:_uploadImages,icon:uploading?const SizedBox(width:18,height:18,child:CircularProgressIndicator(strokeWidth:2)):const Icon(Icons.cloud_upload_outlined),label:Text(imageUrls.isEmpty?'آپلود عکس‌ها':'عکس‌ها آپلود شد ✓'))),
   const SizedBox(height:12),TextField(controller:title,decoration:const InputDecoration(labelText:'عنوان آگهی',hintText:'مثلاً آیفون ۱۳ کارکرده سالم',border:OutlineInputBorder())),const SizedBox(height:10),
   DropdownButtonFormField<String>(value:category.isEmpty?null:category,decoration:const InputDecoration(labelText:'دسته‌بندی',border:OutlineInputBorder()),items:cats.map((c)=>DropdownMenuItem(value:c,child:Text(c))).toList(),onChanged:(v)=>setState(()=>category=v??'')),const SizedBox(height:10),
   TextField(controller:price,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'قیمت',suffixText:'افغانی',border:OutlineInputBorder())),const SizedBox(height:10),TextField(controller:stock,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'تعداد',border:OutlineInputBorder())),const SizedBox(height:10),
   TextField(controller:desc,maxLines:6,textAlignVertical:TextAlignVertical.top,decoration:const InputDecoration(labelText:'توضیحات آگهی',hintText:'وضعیت، مدل، امکانات و نکات مهم را واضح بنویسید…',alignLabelWithHint:true,border:OutlineInputBorder())),const SizedBox(height:18),
   FilledButton.icon(onPressed:uploading?null:(){if(title.text.trim().isEmpty){_msg(Exception('عنوان آگهی را وارد کنید.'));return;}if(category.isEmpty){_msg(Exception('دسته‌بندی را انتخاب کنید.'));return;}if(imageBytes.isNotEmpty&&imageUrls.isEmpty){_msg(Exception('ابتدا عکس‌ها را آپلود کنید.'));return;}Navigator.pop(context,{'title':title.text.trim(),'category':category,'price':double.tryParse(price.text.replaceAll(',',''))??0,'cost_price':0,'stock':int.tryParse(stock.text)??0,'description':desc.text.trim(),'image_url':jsonEncode(imageUrls)});},icon:const Icon(Icons.publish),label:const Text('انتشار آگهی'))
 ]));
}

class AuthScaffold extends StatelessWidget{final String title;final List<Widget> children;const AuthScaffold({super.key,required this.title,required this.children});@override Widget build(BuildContext context)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:520),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[Icon(Icons.storefront_rounded,size:64),const SizedBox(height:12),Text(title,textAlign:TextAlign.center,style:const TextStyle(fontSize:25,fontWeight:FontWeight.bold)),const SizedBox(height:24),...children]))))));}
