name: Build Flutter APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Repair Flutter Project Structure
        run: flutter create . --platforms=android,web

      - name: Ensure Android Internet Permission
        run: |
          MANIFEST="android/app/src/main/AndroidManifest.xml"

          if ! grep -q 'android.permission.INTERNET' "$MANIFEST"; then
            sed -i '/<manifest[^>]*>/a\    <uses-permission android:name="android.permission.INTERNET"/>' "$MANIFEST"
          fi

          echo "=== Android Manifest ==="
          cat "$MANIFEST"

      - name: Install Dependencies
        run: flutter pub get

      - name: Generate Bazarek App Icon
        run: dart run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk

      - name: Build Web
        run: flutter build web --release --base-href /

      - name: Upload Web
        uses: actions/upload-artifact@v4
        with:
          name: bazarek-web
          path: build/web
